- name: Create pods using deployment 
  hosts: kubernetes 
  # become: true
  # user: ubuntu
 
  tasks: 
  - name: delete the previous deployment (ignore if not found)
    command: kubectl delete deployment.apps/cicd-deployment --ignore-not-found

  - name: create a deployment
    command: kubectl apply -f cicd-devops-deployment.yml
